# fly.toml file generated for ohms-api on 2023-04-17T15:11:41+01:00

app = "ohms-api"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  MONGO_URI = "mongodb+srv://timstark:T.starkOHMSDB123@ohms-db.q5gdcnt.mongodb.net/ohmsDB?retryWrites=true&w=majority"
  JWT_SECRET = "nUcNLNsae31foVwbqO8bpHH6UMP/WTr1gNGbhYbKCHEFH/zzI5XM/AORELUcsfrycOjgXNZ+L5CIrB6Z138ao/Xvx/YcuvpXurZHNKpLOjU3kbrl48PoZJEUBjpjmXh5aTuyFhgMBUoED1WxJGDv3/MZyVWf1Gvb/e21wkm+JxYgn0uKmvOjm6sx9BPt7j0/jfGdmIllkg3JjS/TlP8fykIkCEiOhsu+MMWMxoo9OGq1bQSrJUMksdwjwICpnPMCq25bNz2fCUno1In9kLmKSx1qQyLjEqR6qZ2THFbu4Fq0HWOMXmUG5IWspPv4RHjQBerWNo5zx4X0+CSISyRJbA=="
  JWT_EXP = "24h"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
